"""Create voice messages table

Revision ID: b2e4d7c83f4b
Revises: a2e4d7c83f4a
Create Date: 2024-07-20 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2e4d7c83f4b'
down_revision = 'a2e4d7c83f4a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voice_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=False),
        sa.Column('file_data', sa.LargeBinary(), nullable=False),
        sa.Column('original_filename', sa.String(), nullable=True),
        sa.Column('transcribed_text', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_messages_id'), 'voice_messages', ['id'], unique=False)
    op.create_index(op.f('ix_voice_messages_session_id'), 'voice_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_voice_messages_session_id'), table_name='voice_messages')
    op.drop_index(op.f('ix_voice_messages_id'), table_name='voice_messages')
    op.drop_table('voice_messages')
    # ### end Alembic commands ###
